apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s2yk6gj4x-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s2yk6gj4x-dotnet-basic-gitops